### ISSUE TITLE
Duplication of django-polymorphic

### ISSUE THREAD

**Issue by vdboor** [adaptivdesign/django-polymorphism#1]
Hi Guys,

I just noticed this package at django-planet.com, and wondered. Is there a specific reason for not going with https://github.com/chrisglass/django_polymorphic ? I'd be happy to accept pull requests for missing features. It just seems a waste that there are so many polymorphic/MI attempts in Django land, and of which many don't solve the N-query problem or admin integration that django-polymorphic does solve.

**Comment by adaptivdesign** [comment]
Hello :)

Good of you to ask us this question. This project started out as a code snippet for our project django-sellmo. And since then we've been using this in more of our projects, therefor we decided to start a small project ourselves. I've known your project for almost 3 years now, and in the days I started django-sellmo, I wanted to keep polymorphism as clean and explicit as possible. 

For example we require a polymorphic() call to querysets instead of enabling polymorphic lookup behaviour by default. Also we decided to write this project against the latest django version, allowing us to keep our code as simple as possible without resorting to monkey patching, etc. 

Besides the N-query problem we encountered a lot more performance impacts, like N-query select_related and prefetch_related lookups. Especially with the release of Django 1.7 and 1.8 we could implement these things as simple as possible.

Also thanks to the way you've implemented your admin classes, we could easily change the get_queryset modeladmin method and use your admin class with our own polymorphic queryset.

Long story short: Polymorphism is a crucial for our django sellmo project. We wanted explicit usage, great performance (which i do believe your project offers) but since we maintain this code ourselves and we currently are not required to support older django versions, we feel more comfortable writing this small piece of code ourselves.

I do understand your concerns regarding duplicate projects. But right now I don't believe there are that many polymorphic projects out there. Also at the moment this project isn't our main focus, Django-Sellmo is, it isn't documented and we don't ship any examples. But I do think it's healthy for the Django community to offer people a different implementation for polymorphism. This could even help to improve the quality of your project (which I think is a great choice for most Django developers).
